[repo]
name = ""
owner = "ijsKoud"
description = "An open-source customisable solution to storing files in the cloud. âœˆï¸"
license = "MIT"

[project]
icon = "apps/web/public/logo/text.png"
icon_width = "500px"
version = "4.3.1"

[variables]
information = [ "- Customisable âœï¸", "- Blazingly fast thanks to Next.js âš¡", "- File uploading and URL shortening â˜ï¸", "- Password Protection for files ğŸ”", "- Discord Embeds using OG Metadata ğŸ”—", "- 2FA Authentication to protect the vulnerable data ğŸ”„ï¸", "- Gallery and Table viewing options ğŸ“ƒ", "- Support for multiple users using domains ğŸ§‘â€ğŸ¤â€ğŸ§‘", "- Clean and modern design ğŸ–Œï¸", "- User invite-only mode ğŸ“¨", "- Backup import and export functionality ğŸ“‚", "- Easy install using Docker! ğŸš¢" ]
installation = [ "The following guide only shows you the Docker installation steps, for more details visit [the documentation page](https://paperplane.ijskoud.dev/). We are using `~/paperplane` as data folder, `paperplane` as name for the docker container and port `3000` (the first one and not the second one) here, you can customise all the options.\n", "```bash\ndocker pull ghcr.io/ijskoud/paperplane:latest\ndocker run --name=paperplane -d -v ~/paperplane:/paperplane/data -p 3000:3000 ghcr.io/ijskoud/paperplane:latest\n```" ]