name: General Tests
on: [push, pull_request]
jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2

      - name: Install Node v16
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # renovate: tag=v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: (Server) Run ESLint
        run: yarn lint:server
        
      - name: (Web) Run ESLint
        run: yarn lint:web

  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2

      - name: Install Node v16
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # renovate: tag=v2
        with:
          node-version: 16
      
      - name: Install dependencies
        run: yarn install
        
      - name: Generate Prisma Types
        run: yarn prisma:generate

      - name: (Server) TypeScript Compiler
        run: yarn build:server
      
      - name: (Web) TypeScript Compiler
        run: yarn build:web
